const zappfoliodb = [
  {
    _id: { $oid: "66acf1c6dffbe6df4e9123ed" },
    userId: "user_2k5Lyp2ojPMIM8Q9RDFsvV4NqXA",
    userName: "hamsa",
    userEmail: "hemanthsrdev@gmail.com",
    likedinUrl: "https://www.linkedin.com/in/hamsa-k-50b6002b9/",
    linkedinUserData: {
      urn: "ACoAAExxGtsB5vdMHYwWHh3FioaW7zxoLciUJfQ",
      username: "hamsa-k-50b6002b9",
      firstName: "Hamsa",
      lastName: "K",
      isOpenToWork: false,
      isHiring: false,
      profilePicture:
        "https://media.licdn.com/dms/image/D5603AQEcrJLZZYI0ow/profile-displayphoto-shrink_800_800/0/1712584701948?e=1727913600&v=beta&t=kzsjL5nS322j-sDo3BCdWj75n-TmWz7mlGVA90sTn7c",
      summary: "",
      headline: "Attended MVJ College of Engineering, Bangalore, India",
      geo: {
        country: "India",
        city: "Bengaluru, Karnataka",
        full: "Bengaluru, Karnataka, India",
      },
      languages: null,
      educations: [
        {
          start: {
            year: { $numberInt: "2022" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          fieldOfStudy: "Electronics and communication ",
          degree: "Bachelor of Engineering - BE",
          grade: "",
          schoolName: "MVJ College of Engineering, Bangalore, India",
          description: "",
          activities: "",
          url: "https://www.linkedin.com/school/mvj-college-of-engineering-bangalore-india/",
          schoolId: "2817173",
          _id: { $oid: "66acf1c6dffbe6df4e9123ef" },
        },
      ],
      position: null,
      skills: [],
      courses: [],
      certifications: null,
      projects: [],
      _id: { $oid: "66acf1c6dffbe6df4e9123ee" },
      createdAt: { $date: { $numberLong: "1722610118157" } },
      updatedAt: { $date: { $numberLong: "1722610118157" } },
    },
    themesData: {
      slate: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf1c6dffbe6df4e9123f1" },
        },
      },
      vivid: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf1c6dffbe6df4e9123f2" },
        },
      },
      bentodark: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf1c6dffbe6df4e9123f3" },
        },
      },
      twitter: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf1c6dffbe6df4e9123f4" },
        },
      },
      windows95: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf1c6dffbe6df4e9123f5" },
        },
      },
      _id: { $oid: "66acf1c6dffbe6df4e9123f0" },
    },
    __v: { $numberInt: "0" },
  },
  {
    _id: { $oid: "66acf301026156fe51f20ebe" },
    userId: "user_2jF5FDphi5T4fTiADSs3uZOiQ1m",
    userName: "hemanth_ap",
    userEmail: "applicationcomputer257@gmail.com",
    likedinUrl: "https://www.linkedin.com/in/hemanth-gowda-31a7532a7/",
    linkedinUserData: {
      urn: "ACoAAEn4rwYBRInClkbUnutKkLH-2p7lo8bzbn0",
      username: "hemanth-gowda-31a7532a7",
      firstName: "hemanth",
      lastName: "gowda",
      isOpenToWork: false,
      isHiring: false,
      profilePicture:
        "https://media.licdn.com/dms/image/D5603AQHV-jnA3uSbYA/profile-displayphoto-shrink_800_800/0/1704031031513?e=1727913600&v=beta&t=n62q1j5g2dY4UO5sP5NcOG1sapR7aYl51XEB4ZACYUk",
      summary:
        "Passionate developer with a completed 100-day code challenge, deeply involved in the tech world and experienced in web and mobile development. Proficient in JavaScript, Next.js, React.js, Node.js, Tailwind CSS, Kotlin, and Jetpack Compose. Actively participating in hackathons.",
      headline:
        "building zapfolio transforming linkedIn profiles into stunning portfolios in seconds.",
      geo: {
        country: "India",
        city: "Bengaluru, Karnataka",
        full: "Bengaluru, Karnataka, India",
      },
      languages: [
        {
          name: "English",
          proficiency: "PROFESSIONAL_WORKING",
          _id: { $oid: "66acf301026156fe51f20ec0" },
        },
        {
          name: "Hindi",
          proficiency: "LIMITED_WORKING",
          _id: { $oid: "66acf301026156fe51f20ec1" },
        },
        {
          name: "Kannada",
          proficiency: "NATIVE_OR_BILINGUAL",
          _id: { $oid: "66acf301026156fe51f20ec2" },
        },
      ],
      educations: [
        {
          start: {
            year: { $numberInt: "2022" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "2025" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          fieldOfStudy: "Computer Programming",
          degree: "BCA",
          grade: "",
          schoolName: "REVA University",
          description: "",
          activities: "",
          url: "https://www.linkedin.com/school/reva-university/",
          schoolId: "9415817",
          _id: { $oid: "66acf301026156fe51f20ec3" },
        },
      ],
      position: [
        {
          companyName: "Zapfolio",
          companyUsername: "zapfolio",
          companyURL: "https://www.linkedin.com/company/zapfolio/",
          companyLogo:
            "https://media.licdn.com/dms/image/D560BAQFqk7Yyz1T2Cg/company-logo_400_400/0/1718461806007/webpolio_logo?e=1730937600&v=beta&t=T1opJMD0jDQfxX0bnv-0Qywr5aq2WHEStF-PuVQufeQ",
          companyIndustry: "Computer Software",
          companyStaffCountRange: "2 - 10",
          title: "Founder",
          location: "Bengaluru, Karnataka, India",
          description: "",
          employmentType: "Full-time",
          start: {
            year: { $numberInt: "2024" },
            month: { $numberInt: "7" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          _id: { $oid: "66acf301026156fe51f20ec4" },
        },
      ],
      skills: [
        "Next.js",
        "TypeScript",
        "Bash",
        "Git",
        "Amazon Web Services (AWS)",
        "NE",
        "JavaScript",
        "Appwrite",
        "MongoDB",
        "Express.js",
        "Kotlin",
        "Node.js",
        "Tailwind CSS",
        "Android Jetpack",
        "appwrite",
        "Cascading Style Sheets (CSS)",
        "HTML",
        "React Native",
        "React.js",
        "Tech Savy",
        "Research Skills",
      ],
      courses: [],
      certifications: [
        {
          name: "Certificate of Participation in WebCraft",
          start: {
            year: { $numberInt: "2024" },
            month: { $numberInt: "4" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "Unstop ",
            universalName: "unstop",
            logo: "https://media.licdn.com/dms/image/D560BAQHqqREuYOZewQ/company-logo_200_200/0/1701272685881/unstop_logo?e=1730937600&v=beta&t=V6EnWded-7lvaePuBy0HV2pAQs9sSe3MMDAWB8prUSc",
          },
          authority: "Unstop ",
          _id: { $oid: "66acf301026156fe51f20ec5" },
        },
        {
          name: "TECH QUEST NATIONAL LEVEL HACKATHON",
          start: {
            year: { $numberInt: "2024" },
            month: { $numberInt: "4" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "St. Joseph's University",
            universalName: "sjcbengaluru",
            logo: "https://media.licdn.com/dms/image/D560BAQEgxZ2WlrCIeg/company-logo_200_200/0/1714650077723/sjcbengaluru_logo?e=1730937600&v=beta&t=g2Rpt84DVo9BhIsHlNs4wsz-nNG-Nq1qM7huOaMRD3A",
          },
          authority: "St. Joseph's University ",
          _id: { $oid: "66acf301026156fe51f20ec6" },
        },
        {
          name: "HACKITE",
          start: {
            year: { $numberInt: "2024" },
            month: { $numberInt: "3" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "IEDC Mahagurutech",
            universalName: "iedc-mahagurutech",
            logo: "https://media.licdn.com/dms/image/D4D0BAQGjGmQGccQ88g/company-logo_200_200/0/1667847019974/iedc_mahagurutech_logo?e=1730937600&v=beta&t=_dbxvJ4XoBXvD7F9QvFDOIT0WFCkYoCmPd3EbmT1Lk4",
          },
          authority: "IEDC Mahagurutech",
          _id: { $oid: "66acf301026156fe51f20ec7" },
        },
        {
          name: "Ultimate NextJS Course - Learn By Building",
          start: {
            year: { $numberInt: "2023" },
            month: { $numberInt: "11" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "codedamn",
            universalName: "codedamn",
            logo: "https://media.licdn.com/dms/image/v2/C4D0BAQGafuen6FbNnA/company-logo_200_200/company-logo_200_200/0/1630536891944/codedamn_logo?e=1730937600&v=beta&t=yeZc0DZ9J35ptiOw9g1DW6eA8drIyEMeKj9WANvOZdE",
          },
          authority: "codedamn",
          _id: { $oid: "66acf301026156fe51f20ec8" },
        },
        {
          name: "Certificate of Participation in Innovatrix: The Grand Hackathon of Avenir'23 Beyond Infinity, The Annual Techno-Management Fest",
          start: {
            year: { $numberInt: "2023" },
            month: { $numberInt: "6" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "Unstop ",
            universalName: "unstop",
            logo: "https://media.licdn.com/dms/image/D560BAQHqqREuYOZewQ/company-logo_200_200/0/1701272685881/unstop_logo?e=1730937600&v=beta&t=V6EnWded-7lvaePuBy0HV2pAQs9sSe3MMDAWB8prUSc",
          },
          authority: "Unstop ",
          _id: { $oid: "66acf301026156fe51f20ec9" },
        },
        {
          name: "FantomCode",
          start: {
            year: { $numberInt: "2023" },
            month: { $numberInt: "5" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "RV Institute of Technology and Management",
            universalName: "rv-institute-of-technology-and-management",
            logo: "https://media.licdn.com/dms/image/D560BAQGHu08pqMwCtw/company-logo_200_200/0/1700567195085/rv_institute_of_technology_and_management_logo?e=1730937600&v=beta&t=Y2rP8S3C3awRuBZ16crU9RUxKKfu8Y5oKH8MviJ2eFQ",
          },
          authority: "RV Institute of Technology and Management",
          _id: { $oid: "66acf301026156fe51f20eca" },
        },
        {
          name: "Code2Execute",
          start: {
            year: { $numberInt: "2023" },
            month: { $numberInt: "4" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "e2eHiring",
            universalName: "e2ehiring",
            logo: "https://media.licdn.com/dms/image/C560BAQE_7sdW8ZSkqw/company-logo_200_200/0/1662870459112/e2ehiring_logo?e=1730937600&v=beta&t=8n_v1MhmvL_lbFTRO5Zgs2usiw0xIY-GFRqEVUrSU_k",
          },
          authority: "e2eHiring",
          _id: { $oid: "66acf301026156fe51f20ecb" },
        },
        {
          name: "Runner Up For ABHYUDAY 7.0 Design Jam ",
          start: {
            year: { $numberInt: "2023" },
            month: { $numberInt: "3" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "Ramaiah Institute Of Technology",
            universalName: "m.s.-ramaiah-institute-of-technology",
            logo: "https://media.licdn.com/dms/image/C4D0BAQGgBgaivzxtSQ/company-logo_200_200/0/1631351693651?e=1730937600&v=beta&t=mjuXyqgYGKvIOn59-S8OfsU2aeB8o_nyXqCJg_XtXPY",
          },
          authority: "Ramaiah Institute Of Technology",
          _id: { $oid: "66acf301026156fe51f20ecc" },
        },
        {
          name: "Pratibha Puraskara (Meritorious Award)",
          start: {
            year: { $numberInt: "2022" },
            month: { $numberInt: "3" },
            day: { $numberInt: "0" },
          },
          end: {
            year: { $numberInt: "0" },
            month: { $numberInt: "0" },
            day: { $numberInt: "0" },
          },
          company: {
            name: "Seshadripuram First Grade College (S.F.G.C), Bengaluru",
            universalName: "seshadripuram-first-grade-college",
            logo: "https://media.licdn.com/dms/image/D560BAQGeWIu7NAKpgg/company-logo_200_200/0/1706815594225?e=1730937600&v=beta&t=UUORd0Ic5PFYJcnxNWc4RpWvon00kdpO7AltC21jbvQ",
          },
          authority: "Seshadripuram First Grade College (S.F.G.C), Bengaluru",
          _id: { $oid: "66acf301026156fe51f20ecd" },
        },
      ],
      projects: [
        {
          title: "Mangachi",
          description:
            "web application that serves as a platform for manga enthusiasts to share and upload their own manga creations",
          _id: { $oid: "66acf301026156fe51f20ece" },
        },
      ],
      _id: { $oid: "66acf301026156fe51f20ebf" },
      createdAt: { $date: { $numberLong: "1722610433921" } },
      updatedAt: { $date: { $numberLong: "1722610433921" } },
    },
    themesData: {
      slate: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf301026156fe51f20ed0" },
        },
      },
      vivid: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf301026156fe51f20ed1" },
        },
      },
      bentodark: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf301026156fe51f20ed2" },
        },
      },
      twitter: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf301026156fe51f20ed3" },
        },
      },
      windows95: {
        componentsToShow: {
          summary: true,
          headline: true,
          geo: true,
          languages: true,
          educations: true,
          position: true,
          skills: true,
          courses: true,
          certifications: true,
          projects: true,
          resume: true,
          _id: { $oid: "66acf301026156fe51f20ed4" },
        },
      },
      _id: { $oid: "66acf301026156fe51f20ecf" },
    },
    __v: { $numberInt: "0" },
  },
];
