import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderNav } from "@/components/component/headerNav"

const inter = Inter({ subsets: ["latin"] });

import localFont from "next/font/local"

const localfont = localFont({
  src: './fonts/Euclid Circular A Regular.ttf',
  display: 'swap'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={localfont.className}>
        <HeaderNav />
        {children}</body>
    </html>
  );
}
