import { UserDetailedObjectType } from "@/lib/userDeatailed.types";

export const userDetailedObject: UserDetailedObjectType[] = [
  {
    urn: "ACoAAEn4rwYBRInClkbUnutKkLH-2p7lo8bzbn0",
    username: "hemanth-gowda-31a7532a7",
    firstName: "hemanth",
    lastName: "gowda",
    isOpenToWork: false,
    isHiring: false,
    profilePicture:
      "https://media.licdn.com/dms/image/D5603AQHV-jnA3uSbYA/profile-displayphoto-shrink_800_800/0/1704031031513?e=1724889600\u0026v=beta\u0026t=7ma5InI-Yn71AvX8SWU6ZQ1tpvpHQqvicOSCc_i2jf8",
    summary:
      "Passionate developer with a completed 100-day code challenge, deeply involved in the tech world and experienced in web and mobile development. Proficient in JavaScript, Next.js, React.js, Node.js, Tailwind CSS, Kotlin, and Jetpack Compose. Actively participating in hackathons.",
    headline: "Full Stack Engineer at web-polio",
    geo: {
      country: "India",
      city: "Bengaluru, Karnataka",
      full: "Bengaluru, Karnataka, India",
    },
    languages: [
      { name: "English", proficiency: "PROFESSIONAL_WORKING" },
      { name: "Hindi", proficiency: "LIMITED_WORKING" },
      { name: "Kannada", proficiency: "NATIVE_OR_BILINGUAL" },
    ],
    educations: [
      {
        start: { year: 2022, month: 0, day: 0 },
        end: { year: 2025, month: 0, day: 0 },
        fieldOfStudy: "Computer Programming",
        degree: "BCA",
        grade: "",
        schoolName: "REVA University",
        description: "",
        activities: "",
        url: "https://www.linkedin.com/school/reva-university/",
        schoolId: "9415817",
      },
    ],
    position: null,
    skills: [
      "Next.js",
      "TypeScript",
      "Bash",
      "Git",
      "Amazon Web Services (AWS)",
      "NE",
      "JavaScript",
      "Appwrite",
      "MongoDB",
      "Express.js",
      "Kotlin",
      "Node.js",
      "Tailwind CSS",
      "Android Jetpack",
      "appwrite",
      "Cascading Style Sheets (CSS)",
      "HTML",
      "React Native",
      "React.js",
      "Tech Savy",
      "Research Skills",
    ],
    courses: null,
    certifications: [
      {
        name: "Certificate of Participation in WebCraft",
        start: { year: 2024, month: 4, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "Unstop ",
        company: {
          name: "Unstop ",
          universalName: "unstop",
          logo: "https://media.licdn.com/dms/image/D560BAQHqqREuYOZewQ/company-logo_200_200/0/1701272685881/unstop_logo?e=1727308800\u0026v=beta\u0026t=WLrO0EXwvmb_y1aKyj04mlgARAybwvvgzM5BfM83YsE",
        },
      },
      {
        name: "TECH QUEST NATIONAL LEVEL HACKATHON",
        start: { year: 2024, month: 4, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "St. Joseph's University ",
        company: {
          name: "St. Joseph's University",
          universalName: "sjcbengaluru",
          logo: "https://media.licdn.com/dms/image/D560BAQEgxZ2WlrCIeg/company-logo_200_200/0/1714650077723/sjcbengaluru_logo?e=1727308800\u0026v=beta\u0026t=eT3taJXZnZOaUQ1bFcRhWufMAXyCUB5b8wZgQFaIXaQ",
        },
      },
      {
        name: "HACKITE",
        start: { year: 2024, month: 3, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "IEDC Mahagurutech",
        company: {
          name: "IEDC Mahagurutech",
          universalName: "iedc-mahagurutech",
          logo: "https://media.licdn.com/dms/image/D4D0BAQGjGmQGccQ88g/company-logo_200_200/0/1667847019974/iedc_mahagurutech_logo?e=1727308800\u0026v=beta\u0026t=TEHFj72hMRfUshQT_rBn5Q-DYajpl3vcrw9zqlDtGXI",
        },
      },
      {
        name: "Ultimate NextJS Course - Learn By Building",
        start: { year: 2023, month: 11, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "codedamn",
        company: {
          name: "codedamn",
          universalName: "codedamn",
          logo: "https://media.licdn.com/dms/image/C4D0BAQGafuen6FbNnA/company-logo_200_200/0/1630536891944/codedamn_logo?e=1727308800\u0026v=beta\u0026t=gKWucUQ4TCLlXtaqf3BQesZhfHEXTtjDNcM5uEO72TA",
        },
      },
      {
        name: "Certificate of Participation in Innovatrix: The Grand Hackathon of Avenir'23 Beyond Infinity, The Annual Techno-Management Fest",
        start: { year: 2023, month: 6, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "Unstop ",
        company: {
          name: "Unstop ",
          universalName: "unstop",
          logo: "https://media.licdn.com/dms/image/D560BAQHqqREuYOZewQ/company-logo_200_200/0/1701272685881/unstop_logo?e=1727308800\u0026v=beta\u0026t=WLrO0EXwvmb_y1aKyj04mlgARAybwvvgzM5BfM83YsE",
        },
      },
      {
        name: "FantomCode",
        start: { year: 2023, month: 5, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "RV Institute of Technology and Management",
        company: {
          name: "RV Institute of Technology and Management",
          universalName: "rv-institute-of-technology-and-management",
          logo: "https://media.licdn.com/dms/image/D560BAQGHu08pqMwCtw/company-logo_200_200/0/1700567195085/rv_institute_of_technology_and_management_logo?e=1727308800\u0026v=beta\u0026t=88C_m8m8tl13MqEet29A7S9-mrFYOU9wN9ZaQY5uCu4",
        },
      },
      {
        name: "Code2Execute",
        start: { year: 2023, month: 4, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "e2eHiring",
        company: {
          name: "e2eHiring",
          universalName: "e2ehiring",
          logo: "https://media.licdn.com/dms/image/C560BAQE_7sdW8ZSkqw/company-logo_200_200/0/1662870459112/e2ehiring_logo?e=1727308800\u0026v=beta\u0026t=873B-fj7bLkgeDWfWv_7srKYcKsjEhiBRQJ8tmgjVl4",
        },
      },
      {
        name: "Runner Up For ABHYUDAY 7.0 Design Jam ",
        start: { year: 2023, month: 3, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "Ramaiah Institute Of Technology",
        company: {
          name: "Ramaiah Institute Of Technology",
          universalName: "m.s.-ramaiah-institute-of-technology",
          logo: "https://media.licdn.com/dms/image/C4D0BAQGgBgaivzxtSQ/company-logo_200_200/0/1631351693651?e=1727308800\u0026v=beta\u0026t=DUfJusD9tJJg23-x3b1CXBOTKRgMgzkZZKMva942U4E",
        },
      },
      {
        name: "Pratibha Puraskara (Meritorious Award)",
        start: { year: 2022, month: 3, day: 0 },
        end: { year: 0, month: 0, day: 0 },
        authority: "Seshadripuram First Grade College (S.F.G.C), Bengaluru",
        company: {
          name: "Seshadripuram First Grade College (S.F.G.C), Bengaluru",
          universalName: "seshadripuram-first-grade-college",
          logo: "https://media.licdn.com/dms/image/D560BAQGeWIu7NAKpgg/company-logo_200_200/0/1706815594225?e=1727308800\u0026v=beta\u0026t=CqLUrYm6aNWIBHUoC1ZrYSTxxP1--jw9bngmAqRcvcg",
        },
      },
    ],
    projects: [
      {
        title: "Mangachi",
        description:
          "web application that serves as a platform for manga enthusiasts to share and upload their own manga creations",
        start: { year: 0, month: 0, day: 0 },
        end: { year: 0, month: 0, day: 0 },
      },
    ],
  },
];
